Decorator addition of classes, modification of neceassary tests and addition of decorator tests
Birdbh/Engicoders pull request #187
Opened 2024-03-22 20:22 UTC by Birdbh

Fixes #185

2024-03-22 20:29 UTC, JamesShadowfyre requested changes
This design pattern needs some documentation. Please update with some requires and modifies comments so it is understood how to use this pattern for future additions to the code.

2024-03-22 20:29 UTC, JamesShadowfyre commented on src/sensors/DecoratorPattern.py
> +class SensorDataProcessor:
Can you add some specification to this decorator pattern class? Update with comments explaining requires/modifies/effects

2024-03-22 20:29 UTC, JamesShadowfyre commented on src/sensors/DecoratorPattern.py
> +        "Delegate attribute access to the decorated sensor object"
```suggestion
       # "Delegate attribute access to the decorated sensor object"
```

2024-03-22 20:29 UTC, JamesShadowfyre commented on src/sensors/DecoratorPattern.py
> +        "Delegate attribute access to the decorated sensor object"
Make clear its a comment

2024-03-22 21:14 UTC, Birdbh commented
@JamesShadowfyre Based on your feedback I have added Requirments, Modifies, and Effects to fully explain how the decorator pattern is implemented and its intended functionality

2024-03-23 01:23 UTC, brkykrclk approved these changes
Thank god sensor.py didnt change this time, thank you for the update

2024-03-23 01:27 UTC, Reebs296 approved these changes
Looks good to me, check checkkkkk!

2024-03-23 01:30 UTC, Birdbh reviewed
Changes are fixed, modifies/requires/effects put together

2024-03-23 01:43 UTC, Jcp149 approved these changes
tests pass, looks great, i think the design pattern will do this project very well in the long run and make it easier to comprehend the object!

2024-03-23 01:44 UTC, brkykrclk approved these changes
Ok cool sensor.py still same thank youu

2024-03-23 01:49 UTC, merged