Create SuperUser Class
Birdbh/Engicoders pull request #197
Opened 2024-03-24 22:02 UTC by JamesShadowfyre

This class adds a SuperUser to the program, which gains premium features. 
Addresses issue #166 , waiting for issue #196 to be complete. 
PR is here to confirm pipeline issues addressed ahead of merge.

2024-03-25 03:03 UTC, Birdbh requested changes
This does not pass the testing pipeline. Upon closer inspection the short error summary is:
==================================================================== short test summary info ==================================================================== 
ERROR tests/test_superUser.py::test_logging_in - sqlite3.OperationalError: database is locked
ERROR tests/test_user.py::test_register - sqlite3.OperationalError: database is locked

2024-03-25 03:06 UTC, JamesShadowfyre commented
> This does not pass the testing pipeline. Upon closer inspection the short error summary is: ==================================================================== short test summary info ==================================================================== ERROR tests/test_superUser.py::test_logging_in - sqlite3.OperationalError: database is locked ERROR tests/test_user.py::test_register - sqlite3.OperationalError: database is locked

I am aware, that's why it had no reviewers assigned. It is an interesting case, as the tests pass individually. 
Its only when run at a group that certain tests fail. Wanted to see if on repo it passed or not

2024-03-25 06:27 UTC, JamesShadowfyre commented on src/flaskr/login.py
> +                    hasher.update(bytes(password, 'utf8'))
why didnt it catch this before?

2024-03-29 19:08 UTC, Birdbh approved these changes
Looks good, when you merge though there will be multiple conflicts with main because home.html, home.py, Prediction, and a number of tests relating to those have passed. There should be no conflict between what you have done and those files though just that they have changes since what you did. You can either rebase now or resolve the merge conflicts when you merge.

2024-03-29 21:02 UTC, Jcp149 approved these changes
Looks great, very cool that we are hashing the passwords now like the flask tutorial

2024-03-30 00:13 UTC, merged