Issue226: Add in Alarm Alert Functionality to home.html
Birdbh/Engicoders pull request #235
Opened 2024-04-01 20:31 UTC by Reebs296

Fixes #226

2024-04-01 20:32 UTC, Reebs296 commented
I will fix formatting in a separate issue.

2024-04-01 20:40 UTC, JamesShadowfyre approved these changes
Side bar looks good on various screen sizes. As long as this matches what @brkykrclk is currently implementing for alarm functionality, this is approved.

2024-04-01 23:37 UTC, Jcp149 commented
im not in love with the new design with a side bar for the alarms, and the alarm text for max and min is not formatted perfect there is an "alarm" right next to the input box

2024-04-01 23:39 UTC, Reebs296 commented
@Jcp149 can you show me what you see? I didnt have those issues. This was the layout that Berk requested when we spoke during the previous lab session. Right now we don't even have alarms working in the backend, so it's just a format template.

2024-04-02 04:50 UTC, Jcp149 commented
<img width="513" alt="Screenshot 2024-04-01 at 9 49 43 PM" src="https://github.com/Birdbh/Engicoders/assets/156832550/500073ea-90f2-45cd-b3ea-125a56ce966b">

2024-04-02 15:04 UTC, JamesShadowfyre requested changes
Lines 10-18 in the Home.html should be added to the form block content. Currently they are cut off from the side bar and half covered.

2024-04-02 15:04 UTC, JamesShadowfyre commented on src/flaskr/templates/main/home.html
These lines below should be added to the indented block

2024-04-02 16:49 UTC, Birdbh approved these changes

2024-04-04 23:30 UTC, Birdbh submitted a review, later dismissed
![image](https://github.com/Birdbh/Engicoders/assets/93006742/6852c02e-275a-4c39-b15b-54a0eab0ade1)
The Alarm sidebar cuts off the chart when displayed.

2024-04-04 23:41 UTC, Reebs296 commented
I have fixed the formatting issue with the charts, please see now.

2024-04-05 03:53 UTC, Jcp149 approved these changes
Looks great. thanks for fixing it all and making it look pretty

2024-04-05 03:57 UTC, merged