Create codeql.yml
Birdbh/Engicoders pull request #43
Opened 2024-02-22 18:34 UTC by Birdbh

Added QL Analysis workflow as a part of the CI/CD pipeline based on professor resources

2024-02-26 19:53 UTC, JamesShadowfyre requested changes
Fixing code

2024-02-26 19:53 UTC, JamesShadowfyre commented on .github/workflows/codeql.yml
> +        language: [ python ]
```suggestion
        language: [ 'python' ]
```

2024-02-27 05:33 UTC, Jcp149 approved these changes
Looks good to me assuming it works when we actually have code to run!

2024-02-28 20:32 UTC, JamesShadowfyre approved these changes
Passes all tests when run now. Looks good to merge!

2024-02-28 20:32 UTC, merged